# Site
name: 'Adivasi'
description: 'Adivasi is a digital time & life journal'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/FuryFaithBlogs/'
disqus: 'demowebsite'


include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:      
    adi:
      name:           Adi
      avatar:         /assets/images/Snow-me.jpg
      bio:            "Hi, I am Aravind by name but Dil se Adi(Adi by heart), the author of Adivasi, the blog that you're currently stalking. I hope you like it!"


 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: adi
      avatar: /assets/images/Snow-me.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]