# Site
name: 'Adivasi'
description: 'Adivasi is just another digital travel & Life Journal. Please read at you own risk!'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/FuryFaithBlogs/'
disqus: 'demowebsite'
email: 'aravind.000.as@gmail.com'


include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:

    Aravind:
      name:         Aravind
      avatar:         /assets/images/Snow-me.jpg
      bio:            "Hi, I am Aravind, the author of Adivasi, the blog you're currently stalking. I hope you like it!"
      email:          aravind.000.as@gmail.com
     

    
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Aravind
      avatar: /assets/images/Snow-me.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
